services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vodamark
      POSTGRES_PASSWORD: vodamark_password
      POSTGRES_DB: vodamark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
